name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  # required for all workflows
  security-events: write
  # required to fetch internal or private CodeQL packs
  packages: read
  contents: read
  actions: read # Required for private repositories

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
        - language: java-kotlin
          build-mode: none # This mode only analyzes Java. Set this to 'autobuild' or 'manual' to analyze Kotlin too.
        - language: javascript-typescript
          build-mode: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK for Build
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4 # v4
        with:
          #config-file: ./.github/workflows/codeql/codeql-config.yml
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-and-quality, security-extended
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main
      # - name: Build
      #   run: |
      #     ./configure
      #     make
      
      # If the analyze step fails for one of the languages you are analyzing with
      # "We were unable to automatically build your code", modify the matrix above
      # to set the build mode to "manual" for that language. Then modify this step
      # to build your code.
      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
      - name: Build with Gradle
        if: matrix.build-mode == 'manual'
        shell: bash
        run: |
          ./gradlew build

      - name: CodeQL Scan
        uses: github/codeql-action/analyze@v4 # v4

      # This step is required to remove malformed data from the CodeQL output
      # It may be possible to remove in future iterations
      - name: Post-Process Output
        run: |
          python3 -m pip install nasa-scrub

          results_dir=`realpath ${{ github.workspace }}/../results`
          sarif_files=`find $results_dir -name '*.sarif'`

          for sarif_file in $sarif_files
          do
            output_file="$results_dir/$(basename $sarif_file .sarif)_stripped.sarif"

            python3 -m scrub.tools.parsers.translate_results $sarif_file $output_file ${{ github.workspace }} sarifv2.1.0
          done

          echo "RESULTS_DIR=$results_dir" >> $GITHUB_ENV

      # This step makes the analysis artifacts available for download
      # This can be helpful for debugging and archive purposes
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: codeql-artifacts
          path: ${{ env.RESULTS_DIR }}

      - name: Cache SonarQube packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info